spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/space_walk_project
    username: spring_user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    token:
      secret-key: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
      expire-length: 3600000